### Регистрация пользователя
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "bivekipro@gmail.com",
  "fullName": "Данилов Лев Ильич"
}

### Авторизация пользователя
POST https://api.intelectpravo.ru/auth/login
Content-Type: application/json

{
  "email": "bivekipro@gmail.com"
}

### Верефикация (4-ех значный код)
POST https://api.intelectpravo.ru/auth/verify
Content-Type: application/json

{
  "email": "bivekipro@gmail.com",
  "code": "6529"
}