### Тест получения базового профиля
GET http://localhost:3000/profile/basic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY4MjI4NiwiZXhwIjoxNzI2NzY4Njg2fQ.XlvaTmSX5pmB0FNbFbsWKKMVTbFQ0MeYfBbcU_uBJQU

###

### Тест обновления профиля для подтверждения
POST http://localhost:3000/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U

{
  "fullName": "Данилов Лев Ильич",
  "birthDate": "2005-07-12",
  "address": "ул. 6-я Сокольская, д. 6, г. Иваново",
  "passportSeries": "2419",
  "passportNumber": "955212",
  "passportIssuedBy": "УФМС России",
  "passportIssuedDate": "2019-07-17",
  "email": "bivekild@yandex.ru",
  "phoneNumber": "+79611177205"
}

###

### Тест загрузки фото документа
POST http://localhost:3000/profile/upload-photo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U
Content-Type: multipart/form-data

# Пример использования файла для загрузки
@documentPhoto=@/path/to/photo.jpg

###

### Тест подтверждения профиля
POST https://api.intelectpravo.ru/profile/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U

###

### Тест добавления банковских реквизитов
POST http://localhost:3000/profile/bank-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U

{
  "cardNumber": "1234567812345678",
  "accountNumber": "12345678901234567890",
  "corrAccount": "09876543210987654321",
  "bic": "044525225"
}

### Получение банковских реквезитов
GET http://localhost:3000/profile/bank-details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U