### Создание черновика продажи
POST http://localhost:3000/sale/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE
Content-Type: multipart/form-data

{
  "title": "Название произведения",
  "description": "Описание произведения",
  "price": 1000,
  "accountNumber": "12345678901234567890",
  "saleType": "license",
  "isExclusive": true,
  "licenseTerm": 5
}

###

### Тест загрузки документа
POST http://localhost:3000/sale/upload-file
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiaXZla2lwcm9AZ21haWwuY29tIiwiZnVsbE5hbWUiOiLQlNCw0L3QuNC70L7QsiDQm9C10LIg0JjQu9GM0LjRhyIsImlhdCI6MTcyNjY1MzkxMCwiZXhwIjoxNzI2NzQwMzEwfQ.FOPjXjJWN67DFX0LRwK_8mQrU_wZIWCerfOSfckbd1U
Content-Type: multipart/form-data

# Пример использования файла для загрузки
@file=@/path/to/photo.jpg

###

### Получение всех продаж
GET http://localhost:3000/sale/sales
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE

{
  "limit": 0,
  "offset": 10,
}

###

### Покупка
GET http://localhost:3000/sale/user-buy?sid=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjcwMzEwNDYsImV4cCI6MTcyNzExNzQ0Nn0._ML1kf5WMhbMAl3x_R-tjin178cAmpBykivRs5w6tYg
Content-Type: application/json

###

### Пометить оплаченым
GET http://localhost:3000/sale/user-markPaid?sid=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE
Content-Type: application/json

###

### Получение всех файлов пользователя, которые не куплены и не проданы
GET http://localhost:3000/sale/user-sales
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE

###

### Получение купленых файлов пользователя
GET http://localhost:3000/sale/user-boughts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE

###

### Получение проданых файлов пользователя
GET http://localhost:3000/sale/user-selled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2bC5lYmVsLnRtQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJpYXQiOjE3MjY5MzcyMTcsImV4cCI6MTcyNzAyMzYxN30.buXqH5diTESKN9SY0dQuiFGJ4Ug9eMiugr9bhTKDxnE

###

